<a href="https://colab.research.google.com/github/saptarshidas219/00-rahul/blob/master/olympic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
pip install kagglehub[pandas-datasets]

Requirement already satisfied: kagglehub[pandas-datasets] in /usr/local/lib/python3.12/dist-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (0.1.16)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (26.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (4.67.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (2.2.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kagglesdk<1.0,>=0.1.14->kagglehub[pandas-datasets]) (5.29.6)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (2026.2.25)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->kagglehub[pandas-datasets]) (1.17.0)

In [4]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "athlete_events.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "heesoo37/120-years-of-olympic-history-athletes-and-results",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

/tmp/ipykernel_14515/559469201.py:8: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Downloading to /root/.cache/kagglehub/datasets/heesoo37/120-years-of-olympic-history-athletes-and-results/versions/2/athlete_events.csv...

100%|██████████| 5.43M/5.43M [00:00<00:00, 45.9MB/s]

Extracting zip of athlete_events.csv...

In [6]:
df.head(5)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      271116 non-null  int64
 1   Name    271116 non-null  object
 2   Sex     271116 non-null  object
 3   Age     261642 non-null  float64
 4   Height  210945 non-null  float64
 5   Weight  208241 non-null  float64
 6   Team    271116 non-null  object
 7   NOC     271116 non-null  object
 8   Games   271116 non-null  object
 9   Year    271116 non-null  int64
 10  Season  271116 non-null  object
 11  City    271116 non-null  object
 12  Sport   271116 non-null  object
 13  Event   271116 non-null  object
 14  Medal   39783 non-null   object
dtypes: float64(3), int64(2), object(10)
memory usage: 31.0+ MB

In [10]:
df.dtypes

ID          int64
Name       object
Sex        object
Age       float64
Height    float64
Weight    float64
Team       object
NOC        object
Games      object
Year        int64
Season     object
City       object
Sport      object
Event      object
Medal      object
dtype: object

In [13]:
df.Sex.unique()

array(['M', 'F'], dtype=object)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 18 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   ID        271116 non-null  int64
 1   Name      271116 non-null  object
 2   Sex       271116 non-null  category
 3   Age       261642 non-null  float64
 4   Height    210945 non-null  float64
 5   Weight    208241 non-null  float64
 6   Team      271116 non-null  object
 7   NOC       271116 non-null  object
 8   Games     271116 non-null  object
 9   Year      271116 non-null  int64
 10  Season    271116 non-null  object
 11  City      271116 non-null  object
 12  Sport     271116 non-null  object
 13  Event     271116 non-null  object
 14  Medal     39783 non-null   object
 15  Category  271116 non-null  category
 16  M         271116 non-null  object
 17  F         271116 non-null  object
dtypes: category(2), float64(3), int64(2), object(11)
memory usage: 33.6+ MB

In [34]:
df['Sex']=df.Sex.astype('category')

In [39]:
df=df.drop(['M','F'],axis=1)

KeyError: "['M', 'F'] not found in axis"

In [41]:
df.head(3)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,Category
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,M
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,M
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,M

In [46]:
df.Season.unique()

array(['Summer', 'Winter'], dtype=object)

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 16 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   ID        271116 non-null  int64
 1   Name      271116 non-null  object
 2   Sex       271116 non-null  category
 3   Age       261642 non-null  float64
 4   Height    210945 non-null  float64
 5   Weight    208241 non-null  float64
 6   Team      271116 non-null  object
 7   NOC       271116 non-null  object
 8   Games     271116 non-null  object
 9   Year      271116 non-null  int64
 10  Season    271116 non-null  object
 11  City      271116 non-null  object
 12  Sport     271116 non-null  object
 13  Event     271116 non-null  object
 14  Medal     39783 non-null   object
 15  Category  271116 non-null  category
dtypes: category(2), float64(3), int64(2), object(9)
memory usage: 29.5+ MB

In [53]:
dtype_map = {'ID':'int64', 'Name':'string', 'Sex':'category', 'Age':'float64', 'Height':'float64',
             'Weight':'float64', 'Team':'string', 'NOC':'string', 'Games':'string',
       'Year':'int64', 'Season':'string', 'City':'string', 'Sport':'string', 'Event':'string',
             'Medal':'category', 'Category':'category'}

In [54]:
df.astype(dtype_map).dtypes

ID                   int64
Name        string[python]
Sex               category
Age                float64
Height             float64
Weight             float64
Team        string[python]
NOC         string[python]
Games       string[python]
Year                 int64
Season      string[python]
City        string[python]
Sport       string[python]
Event       string[python]
Medal             category
Category          category
dtype: object

In [58]:
df.Medal.unique()

array([nan, 'Gold', 'Bronze', 'Silver'], dtype=object)

In [68]:
df["Medal"]=df.Medal.fillna('No Medal')

In [69]:
df.Medal.unique()

array(['No Medal', 'Gold', 'Bronze', 'Silver'], dtype=object)